import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to Rice Publics
        </h1>
        <button className="btn btn-primary">
          Button
        </button>
      </main>

      <footer>
        Footer text
      </footer>
    </div>
  )
}

export default Home
