import Head from 'next/head'
import { useState, useEffect } from 'react'

export default function Create() {
  return (
    <div>
      <Head>
        <title>Create Event Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Create an Event with this Form
        </h1>
        <div className="form-control w-full max-w-xs">
          <label className="label">
            <span className="label-text">What is the name of your event?</span>
          </label>
          <input type="text" placeholder="Type here" className="input input-bordered w-full max-w-xs" />
        </div>
        <div className="form-control w-full max-w-xs">
          <label className="label">
            <span className="label-text">What is the maximum capacity of your event?</span>
          </label>
          <input type="number" placeholder="Type here" className="input input-bordered w-full max-w-xs" />
        </div>
        <div className="form-control w-full max-w-xs">
          <label className="label">
            <span className="label-text">What is the maximum signup size for your event?</span>
          </label>
          <input type="number" placeholder="Type here" className="input input-bordered w-full max-w-xs" />
        </div>
        <div className="form-control w-full max-w-xs">
          <label className="label">
            <span className="label-text">What is the maximum waitlist size for your event?</span>
          </label>
          <input type="number" placeholder="Type here" className="input input-bordered w-full max-w-xs" />
        </div>
        <div className="form-control">
          <label className="label">
            <span className="label-text">Enter a description for your event here</span>
          </label> 
          <textarea className="textarea textarea-bordered max-w-xs h-24" placeholder="Bio"></textarea>
        </div>
        <div className="form-control w-full max-w-xs">
          <label className="label">
            <span className="label-text">What is the date of your event?</span>
          </label>
          <input type="date" placeholder="Enter valid date" className="input input-bordered w-full max-w-xs" />
        </div>
        <div className="form-control w-full max-w-xs">
          <label className="label">
            <span className="label-text">What is the starting time of your event?</span>
          </label>
          <input type="time" placeholder="Enter valid time" className="input input-bordered w-full max-w-xs" />
        </div>
        <div className="form-control w-full max-w-xs">
          <label className="label">
            <span className="label-text">What is the ending time of your event?</span>
          </label>
          <input type="time" placeholder="Enter valid time" className="input input-bordered w-full max-w-xs" />
        </div>
        <div className="form-control w-full max-w-xs">
          <label className="label">
            <span className="label-text">What is the starting date of registration?</span>
          </label>
          <input type="date" placeholder="Enter valid date" className="input input-bordered w-full max-w-xs" />
        </div>
        <div className="form-control w-full max-w-xs">
          <label className="label">
            <span className="label-text">What is the starting time of registration?</span>
          </label>
          <input type="time" placeholder="Enter valid time" className="input input-bordered w-full max-w-xs" />
        </div>
        <div className="form-control w-full max-w-xs">
          <label className="label">
            <span className="label-text">What is the ending date of registration?</span>
          </label>
          <input type="date" placeholder="Enter valid date" className="input input-bordered w-full max-w-xs" />
        </div>
        <div className="form-control w-full max-w-xs">
          <label className="label">
            <span className="label-text">What is the ending time of registration?</span>
          </label>
          <input type="time" placeholder="Enter valid time" className="input input-bordered w-full max-w-xs" />
        </div>
        <div className="form-control w-full max-w-xs">
          <label className="label">
            <span className="label-text">Enter a unique URL name you want for your event (e.g., nod22)</span>
          </label>
          <input type="text" placeholder="Type here" className="input input-bordered w-full max-w-xs" />
        </div>
      </main>
    </div>
  )
}
