/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [require("daisyui")],

  daisyui: {
    themes: [
      {
        "party owl": {
          "color-scheme": "light",
          primary: "#AC1FB8",
          secondary: "#E9498C",
          accent: "#D9D9D9",
          neutral: "#AC1FB8",
          "base-100": "#FFFFFF",
          info: "#4AA8BF",
          success: "#81328F",
          warning: "#EF8234",
          error: "#EA4034",
        },
      },
      {
        "nocturnal party owl": {
          "color-scheme": "dark",
          primary: "#AC1FB8",
          secondary: "#E9498C",
          accent: "#ede442",
          neutral: "#914099",
          "base-100": "#1c1c1c",
          info: "#4AA8BF",
          success: "#42ed83",
          warning: "#EF8234",
          error: "#EA4034",
        },
      },
      {
        butter: {
          "color-scheme": "light",
          "base-100": "hsl(64, 6%, 14%)",
          neutral: "#8e8d80",
          primary: "#c6c3ac",
          secondary: "#f1edd2",
          accent: "#578f2f",
          info: "#96c1da",
          success: "#8ad89f",
          warning: "#d8c46c",
          error: "#d86c6c",
          default: "#c6c3ac",
        },
      },
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
    ],
    darkTheme: "nocturnal party owl",
  },
}
